template: testify
packages:
  github.com/ivan-prykhodko/pgx-outbox:
    config:
      structname: "mock{{.InterfaceName}}"
    interfaces:
      Acknowledger:
      Dispatcher:
      Processor:
      Provider:
      Publisher:
      Repository:
      Router:
      RowQuerier:
