// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// newMockAcknowledger creates a new instance of mockAcknowledger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAcknowledger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAcknowledger {
	mock := &mockAcknowledger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAcknowledger is an autogenerated mock type for the Acknowledger type
type mockAcknowledger struct {
	mock.Mock
}

type mockAcknowledger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAcknowledger) EXPECT() *mockAcknowledger_Expecter {
	return &mockAcknowledger_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type mockAcknowledger
func (_mock *mockAcknowledger) Ack(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAcknowledger_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type mockAcknowledger_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *mockAcknowledger_Expecter) Ack(ctx any, id any) *mockAcknowledger_Ack_Call {
	return &mockAcknowledger_Ack_Call{Call: _e.mock.On("Ack", ctx, id)}
}

func (_c *mockAcknowledger_Ack_Call) Run(run func(ctx context.Context, id int64)) *mockAcknowledger_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAcknowledger_Ack_Call) Return(err error) *mockAcknowledger_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAcknowledger_Ack_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *mockAcknowledger_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Nack provides a mock function for the type mockAcknowledger
func (_mock *mockAcknowledger) Nack(ctx context.Context, id int64, errMsg error) error {
	ret := _mock.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error) error); ok {
		r0 = returnFunc(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAcknowledger_Nack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nack'
type mockAcknowledger_Nack_Call struct {
	*mock.Call
}

// Nack is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - errMsg error
func (_e *mockAcknowledger_Expecter) Nack(ctx any, id any, errMsg any) *mockAcknowledger_Nack_Call {
	return &mockAcknowledger_Nack_Call{Call: _e.mock.On("Nack", ctx, id, errMsg)}
}

func (_c *mockAcknowledger_Nack_Call) Run(run func(ctx context.Context, id int64, errMsg error)) *mockAcknowledger_Nack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAcknowledger_Nack_Call) Return(err error) *mockAcknowledger_Nack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAcknowledger_Nack_Call) RunAndReturn(run func(ctx context.Context, id int64, errMsg error) error) *mockAcknowledger_Nack_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDispatcher creates a new instance of mockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDispatcher {
	mock := &mockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDispatcher is an autogenerated mock type for the Dispatcher type
type mockDispatcher struct {
	mock.Mock
}

type mockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDispatcher) EXPECT() *mockDispatcher_Expecter {
	return &mockDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) Dispatch(ctx context.Context, msg *Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *Message
func (_e *mockDispatcher_Expecter) Dispatch(ctx any, msg any) *mockDispatcher_Dispatch_Call {
	return &mockDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, msg)}
}

func (_c *mockDispatcher_Dispatch_Call) Run(run func(ctx context.Context, msg *Message)) *mockDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Message
		if args[1] != nil {
			arg1 = args[1].(*Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDispatcher_Dispatch_Call) Return(err error) *mockDispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, msg *Message) error) *mockDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// newMocknlConnector creates a new instance of mocknlConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocknlConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocknlConnector {
	mock := &mocknlConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocknlConnector is an autogenerated mock type for the nlConnector type
type mocknlConnector struct {
	mock.Mock
}

type mocknlConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *mocknlConnector) EXPECT() *mocknlConnector_Expecter {
	return &mocknlConnector_Expecter{mock: &_m.Mock}
}

// ConnectConfig provides a mock function for the type mocknlConnector
func (_mock *mocknlConnector) ConnectConfig(ctx context.Context, config *pgx.ConnConfig) (nlConnection, error) {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for ConnectConfig")
	}

	var r0 nlConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.ConnConfig) (nlConnection, error)); ok {
		return returnFunc(ctx, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.ConnConfig) nlConnection); ok {
		r0 = returnFunc(ctx, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nlConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pgx.ConnConfig) error); ok {
		r1 = returnFunc(ctx, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocknlConnector_ConnectConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectConfig'
type mocknlConnector_ConnectConfig_Call struct {
	*mock.Call
}

// ConnectConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - config *pgx.ConnConfig
func (_e *mocknlConnector_Expecter) ConnectConfig(ctx any, config any) *mocknlConnector_ConnectConfig_Call {
	return &mocknlConnector_ConnectConfig_Call{Call: _e.mock.On("ConnectConfig", ctx, config)}
}

func (_c *mocknlConnector_ConnectConfig_Call) Run(run func(ctx context.Context, config *pgx.ConnConfig)) *mocknlConnector_ConnectConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.ConnConfig
		if args[1] != nil {
			arg1 = args[1].(*pgx.ConnConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocknlConnector_ConnectConfig_Call) Return(nlConnectionMoqParam nlConnection, err error) *mocknlConnector_ConnectConfig_Call {
	_c.Call.Return(nlConnectionMoqParam, err)
	return _c
}

func (_c *mocknlConnector_ConnectConfig_Call) RunAndReturn(run func(ctx context.Context, config *pgx.ConnConfig) (nlConnection, error)) *mocknlConnector_ConnectConfig_Call {
	_c.Call.Return(run)
	return _c
}

// newMocknlConnection creates a new instance of mocknlConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocknlConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocknlConnection {
	mock := &mocknlConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocknlConnection is an autogenerated mock type for the nlConnection type
type mocknlConnection struct {
	mock.Mock
}

type mocknlConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *mocknlConnection) EXPECT() *mocknlConnection_Expecter {
	return &mocknlConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type mocknlConnection
func (_mock *mocknlConnection) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocknlConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mocknlConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mocknlConnection_Expecter) Close(ctx any) *mocknlConnection_Close_Call {
	return &mocknlConnection_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *mocknlConnection_Close_Call) Run(run func(ctx context.Context)) *mocknlConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocknlConnection_Close_Call) Return(err error) *mocknlConnection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocknlConnection_Close_Call) RunAndReturn(run func(ctx context.Context) error) *mocknlConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type mocknlConnection
func (_mock *mocknlConnection) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(arguments) > 0 {
		tmpRet = _mock.Called(ctx, sql, arguments)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, arguments...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, arguments...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, arguments...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocknlConnection_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type mocknlConnection_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - arguments ...any
func (_e *mocknlConnection_Expecter) Exec(ctx any, sql any, arguments ...any) *mocknlConnection_Exec_Call {
	return &mocknlConnection_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, sql}, arguments...)...)}
}

func (_c *mocknlConnection_Exec_Call) Run(run func(ctx context.Context, sql string, arguments ...any)) *mocknlConnection_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocknlConnection_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *mocknlConnection_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *mocknlConnection_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)) *mocknlConnection_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForNotification provides a mock function for the type mocknlConnection
func (_mock *mocknlConnection) WaitForNotification(ctx context.Context) (*pgconn.Notification, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WaitForNotification")
	}

	var r0 *pgconn.Notification
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*pgconn.Notification, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *pgconn.Notification); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgconn.Notification)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocknlConnection_WaitForNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForNotification'
type mocknlConnection_WaitForNotification_Call struct {
	*mock.Call
}

// WaitForNotification is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mocknlConnection_Expecter) WaitForNotification(ctx any) *mocknlConnection_WaitForNotification_Call {
	return &mocknlConnection_WaitForNotification_Call{Call: _e.mock.On("WaitForNotification", ctx)}
}

func (_c *mocknlConnection_WaitForNotification_Call) Run(run func(ctx context.Context)) *mocknlConnection_WaitForNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocknlConnection_WaitForNotification_Call) Return(notification *pgconn.Notification, err error) *mocknlConnection_WaitForNotification_Call {
	_c.Call.Return(notification, err)
	return _c
}

func (_c *mocknlConnection_WaitForNotification_Call) RunAndReturn(run func(ctx context.Context) (*pgconn.Notification, error)) *mocknlConnection_WaitForNotification_Call {
	_c.Call.Return(run)
	return _c
}

// newMockNotificationListener creates a new instance of mockNotificationListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockNotificationListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockNotificationListener {
	mock := &mockNotificationListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockNotificationListener is an autogenerated mock type for the NotificationListener type
type mockNotificationListener struct {
	mock.Mock
}

type mockNotificationListener_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNotificationListener) EXPECT() *mockNotificationListener_Expecter {
	return &mockNotificationListener_Expecter{mock: &_m.Mock}
}

// WaitForNotification provides a mock function for the type mockNotificationListener
func (_mock *mockNotificationListener) WaitForNotification(ctx context.Context, notifyCh chan<- struct{}, errCh chan<- error) {
	_mock.Called(ctx, notifyCh, errCh)
}

// mockNotificationListener_WaitForNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForNotification'
type mockNotificationListener_WaitForNotification_Call struct {
	*mock.Call
}

// WaitForNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - notifyCh chan<- struct{}
//   - errCh chan<- error
func (_e *mockNotificationListener_Expecter) WaitForNotification(ctx any, notifyCh any, errCh any) *mockNotificationListener_WaitForNotification_Call {
	return &mockNotificationListener_WaitForNotification_Call{Call: _e.mock.On("WaitForNotification", ctx, notifyCh, errCh)}
}

func (_c *mockNotificationListener_WaitForNotification_Call) Run(run func(ctx context.Context, notifyCh chan<- struct{}, errCh chan<- error)) *mockNotificationListener_WaitForNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- struct{}
		if args[1] != nil {
			arg1 = args[1].(chan<- struct{})
		}
		var arg2 chan<- error
		if args[2] != nil {
			arg2 = args[2].(chan<- error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockNotificationListener_WaitForNotification_Call) Return() *mockNotificationListener_WaitForNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockNotificationListener_WaitForNotification_Call) RunAndReturn(run func(ctx context.Context, notifyCh chan<- struct{}, errCh chan<- error)) *mockNotificationListener_WaitForNotification_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProcessor creates a new instance of mockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProcessor {
	mock := &mockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProcessor is an autogenerated mock type for the Processor type
type mockProcessor struct {
	mock.Mock
}

type mockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProcessor) EXPECT() *mockProcessor_Expecter {
	return &mockProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type mockProcessor
func (_mock *mockProcessor) Process(ctx context.Context, delivery *Delivery) error {
	ret := _mock.Called(ctx, delivery)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Delivery) error); ok {
		r0 = returnFunc(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type mockProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - delivery *Delivery
func (_e *mockProcessor_Expecter) Process(ctx any, delivery any) *mockProcessor_Process_Call {
	return &mockProcessor_Process_Call{Call: _e.mock.On("Process", ctx, delivery)}
}

func (_c *mockProcessor_Process_Call) Run(run func(ctx context.Context, delivery *Delivery)) *mockProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Delivery
		if args[1] != nil {
			arg1 = args[1].(*Delivery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProcessor_Process_Call) Return(err error) *mockProcessor_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockProcessor_Process_Call) RunAndReturn(run func(ctx context.Context, delivery *Delivery) error) *mockProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProvider creates a new instance of mockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProvider {
	mock := &mockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProvider is an autogenerated mock type for the Provider type
type mockProvider struct {
	mock.Mock
}

type mockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProvider) EXPECT() *mockProvider_Expecter {
	return &mockProvider_Expecter{mock: &_m.Mock}
}

// Provide provides a mock function for the type mockProvider
func (_mock *mockProvider) Provide(ctx context.Context) (<-chan Delivery, <-chan error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 <-chan Delivery
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan Delivery, <-chan error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan Delivery); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// mockProvider_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type mockProvider_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockProvider_Expecter) Provide(ctx any) *mockProvider_Provide_Call {
	return &mockProvider_Provide_Call{Call: _e.mock.On("Provide", ctx)}
}

func (_c *mockProvider_Provide_Call) Run(run func(ctx context.Context)) *mockProvider_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockProvider_Provide_Call) Return(deliveryCh <-chan Delivery, errCh <-chan error) *mockProvider_Provide_Call {
	_c.Call.Return(deliveryCh, errCh)
	return _c
}

func (_c *mockProvider_Provide_Call) RunAndReturn(run func(ctx context.Context) (<-chan Delivery, <-chan error)) *mockProvider_Provide_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPublisher creates a new instance of mockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPublisher {
	mock := &mockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPublisher is an autogenerated mock type for the Publisher type
type mockPublisher struct {
	mock.Mock
}

type mockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPublisher) EXPECT() *mockPublisher_Expecter {
	return &mockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type mockPublisher
func (_mock *mockPublisher) Publish(ctx context.Context, env *Envelope) error {
	ret := _mock.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Envelope) error); ok {
		r0 = returnFunc(ctx, env)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type mockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - env *Envelope
func (_e *mockPublisher_Expecter) Publish(ctx any, env any) *mockPublisher_Publish_Call {
	return &mockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, env)}
}

func (_c *mockPublisher_Publish_Call) Run(run func(ctx context.Context, env *Envelope)) *mockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Envelope
		if args[1] != nil {
			arg1 = args[1].(*Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPublisher_Publish_Call) Return(err error) *mockPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, env *Envelope) error) *mockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRepository creates a new instance of mockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepository {
	mock := &mockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRepository is an autogenerated mock type for the Repository type
type mockRepository struct {
	mock.Mock
}

type mockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRepository) EXPECT() *mockRepository_Expecter {
	return &mockRepository_Expecter{mock: &_m.Mock}
}

// ClaimPending provides a mock function for the type mockRepository
func (_mock *mockRepository) ClaimPending(ctx context.Context, limit int) ([]Message, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPending")
	}

	var r0 []Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]Message, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []Message); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRepository_ClaimPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPending'
type mockRepository_ClaimPending_Call struct {
	*mock.Call
}

// ClaimPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *mockRepository_Expecter) ClaimPending(ctx any, limit any) *mockRepository_ClaimPending_Call {
	return &mockRepository_ClaimPending_Call{Call: _e.mock.On("ClaimPending", ctx, limit)}
}

func (_c *mockRepository_ClaimPending_Call) Run(run func(ctx context.Context, limit int)) *mockRepository_ClaimPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRepository_ClaimPending_Call) Return(messages []Message, err error) *mockRepository_ClaimPending_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *mockRepository_ClaimPending_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]Message, error)) *mockRepository_ClaimPending_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRetryPolicy creates a new instance of mockRetryPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRetryPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRetryPolicy {
	mock := &mockRetryPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRetryPolicy is an autogenerated mock type for the RetryPolicy type
type mockRetryPolicy struct {
	mock.Mock
}

type mockRetryPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRetryPolicy) EXPECT() *mockRetryPolicy_Expecter {
	return &mockRetryPolicy_Expecter{mock: &_m.Mock}
}

// NextRetry provides a mock function for the type mockRetryPolicy
func (_mock *mockRetryPolicy) NextRetry(attempts int) time.Time {
	ret := _mock.Called(attempts)

	if len(ret) == 0 {
		panic("no return value specified for NextRetry")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func(int) time.Time); ok {
		r0 = returnFunc(attempts)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockRetryPolicy_NextRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRetry'
type mockRetryPolicy_NextRetry_Call struct {
	*mock.Call
}

// NextRetry is a helper method to define mock.On call
//   - attempts int
func (_e *mockRetryPolicy_Expecter) NextRetry(attempts any) *mockRetryPolicy_NextRetry_Call {
	return &mockRetryPolicy_NextRetry_Call{Call: _e.mock.On("NextRetry", attempts)}
}

func (_c *mockRetryPolicy_NextRetry_Call) Run(run func(attempts int)) *mockRetryPolicy_NextRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRetryPolicy_NextRetry_Call) Return(time1 time.Time) *mockRetryPolicy_NextRetry_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockRetryPolicy_NextRetry_Call) RunAndReturn(run func(attempts int) time.Time) *mockRetryPolicy_NextRetry_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldRetry provides a mock function for the type mockRetryPolicy
func (_mock *mockRetryPolicy) ShouldRetry(attempts int) bool {
	ret := _mock.Called(attempts)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRetry")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(attempts)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockRetryPolicy_ShouldRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRetry'
type mockRetryPolicy_ShouldRetry_Call struct {
	*mock.Call
}

// ShouldRetry is a helper method to define mock.On call
//   - attempts int
func (_e *mockRetryPolicy_Expecter) ShouldRetry(attempts any) *mockRetryPolicy_ShouldRetry_Call {
	return &mockRetryPolicy_ShouldRetry_Call{Call: _e.mock.On("ShouldRetry", attempts)}
}

func (_c *mockRetryPolicy_ShouldRetry_Call) Run(run func(attempts int)) *mockRetryPolicy_ShouldRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRetryPolicy_ShouldRetry_Call) Return(b bool) *mockRetryPolicy_ShouldRetry_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockRetryPolicy_ShouldRetry_Call) RunAndReturn(run func(attempts int) bool) *mockRetryPolicy_ShouldRetry_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRouter creates a new instance of mockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRouter {
	mock := &mockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRouter is an autogenerated mock type for the Router type
type mockRouter struct {
	mock.Mock
}

type mockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRouter) EXPECT() *mockRouter_Expecter {
	return &mockRouter_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type mockRouter
func (_mock *mockRouter) Resolve(msg *Message) (Route, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 Route
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Message) (Route, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func(*Message) Route); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Message) error); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRouter_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type mockRouter_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - msg *Message
func (_e *mockRouter_Expecter) Resolve(msg any) *mockRouter_Resolve_Call {
	return &mockRouter_Resolve_Call{Call: _e.mock.On("Resolve", msg)}
}

func (_c *mockRouter_Resolve_Call) Run(run func(msg *Message)) *mockRouter_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Message
		if args[0] != nil {
			arg0 = args[0].(*Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRouter_Resolve_Call) Return(route Route, err error) *mockRouter_Resolve_Call {
	_c.Call.Return(route, err)
	return _c
}

func (_c *mockRouter_Resolve_Call) RunAndReturn(run func(msg *Message) (Route, error)) *mockRouter_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRowQuerier creates a new instance of mockRowQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRowQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRowQuerier {
	mock := &mockRowQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRowQuerier is an autogenerated mock type for the RowQuerier type
type mockRowQuerier struct {
	mock.Mock
}

type mockRowQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRowQuerier) EXPECT() *mockRowQuerier_Expecter {
	return &mockRowQuerier_Expecter{mock: &_m.Mock}
}

// QueryRow provides a mock function for the type mockRowQuerier
func (_mock *mockRowQuerier) QueryRow(ctx context.Context, query string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// mockRowQuerier_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type mockRowQuerier_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *mockRowQuerier_Expecter) QueryRow(ctx any, query any, args ...any) *mockRowQuerier_QueryRow_Call {
	return &mockRowQuerier_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{ctx, query}, args...)...)}
}

func (_c *mockRowQuerier_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *mockRowQuerier_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockRowQuerier_QueryRow_Call) Return(row pgx.Row) *mockRowQuerier_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *mockRowQuerier_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) pgx.Row) *mockRowQuerier_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
