// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// newMockAcknowledger creates a new instance of mockAcknowledger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAcknowledger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAcknowledger {
	mock := &mockAcknowledger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAcknowledger is an autogenerated mock type for the Acknowledger type
type mockAcknowledger struct {
	mock.Mock
}

type mockAcknowledger_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAcknowledger) EXPECT() *mockAcknowledger_Expecter {
	return &mockAcknowledger_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type mockAcknowledger
func (_mock *mockAcknowledger) Ack(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAcknowledger_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type mockAcknowledger_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *mockAcknowledger_Expecter) Ack(ctx any, id any) *mockAcknowledger_Ack_Call {
	return &mockAcknowledger_Ack_Call{Call: _e.mock.On("Ack", ctx, id)}
}

func (_c *mockAcknowledger_Ack_Call) Run(run func(ctx context.Context, id int64)) *mockAcknowledger_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAcknowledger_Ack_Call) Return(err error) *mockAcknowledger_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAcknowledger_Ack_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *mockAcknowledger_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Nack provides a mock function for the type mockAcknowledger
func (_mock *mockAcknowledger) Nack(ctx context.Context, id int64, errMsg error) error {
	ret := _mock.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Nack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, error) error); ok {
		r0 = returnFunc(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockAcknowledger_Nack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nack'
type mockAcknowledger_Nack_Call struct {
	*mock.Call
}

// Nack is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - errMsg error
func (_e *mockAcknowledger_Expecter) Nack(ctx any, id any, errMsg any) *mockAcknowledger_Nack_Call {
	return &mockAcknowledger_Nack_Call{Call: _e.mock.On("Nack", ctx, id, errMsg)}
}

func (_c *mockAcknowledger_Nack_Call) Run(run func(ctx context.Context, id int64, errMsg error)) *mockAcknowledger_Nack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAcknowledger_Nack_Call) Return(err error) *mockAcknowledger_Nack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockAcknowledger_Nack_Call) RunAndReturn(run func(ctx context.Context, id int64, errMsg error) error) *mockAcknowledger_Nack_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDispatcher creates a new instance of mockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDispatcher {
	mock := &mockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDispatcher is an autogenerated mock type for the Dispatcher type
type mockDispatcher struct {
	mock.Mock
}

type mockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDispatcher) EXPECT() *mockDispatcher_Expecter {
	return &mockDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type mockDispatcher
func (_mock *mockDispatcher) Dispatch(ctx context.Context, msg *Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type mockDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *Message
func (_e *mockDispatcher_Expecter) Dispatch(ctx any, msg any) *mockDispatcher_Dispatch_Call {
	return &mockDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, msg)}
}

func (_c *mockDispatcher_Dispatch_Call) Run(run func(ctx context.Context, msg *Message)) *mockDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Message
		if args[1] != nil {
			arg1 = args[1].(*Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDispatcher_Dispatch_Call) Return(err error) *mockDispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, msg *Message) error) *mockDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProcessor creates a new instance of mockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProcessor {
	mock := &mockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProcessor is an autogenerated mock type for the Processor type
type mockProcessor struct {
	mock.Mock
}

type mockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProcessor) EXPECT() *mockProcessor_Expecter {
	return &mockProcessor_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type mockProcessor
func (_mock *mockProcessor) Process(ctx context.Context, delivery *Delivery) error {
	ret := _mock.Called(ctx, delivery)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Delivery) error); ok {
		r0 = returnFunc(ctx, delivery)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type mockProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - delivery *Delivery
func (_e *mockProcessor_Expecter) Process(ctx any, delivery any) *mockProcessor_Process_Call {
	return &mockProcessor_Process_Call{Call: _e.mock.On("Process", ctx, delivery)}
}

func (_c *mockProcessor_Process_Call) Run(run func(ctx context.Context, delivery *Delivery)) *mockProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Delivery
		if args[1] != nil {
			arg1 = args[1].(*Delivery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockProcessor_Process_Call) Return(err error) *mockProcessor_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockProcessor_Process_Call) RunAndReturn(run func(ctx context.Context, delivery *Delivery) error) *mockProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// newMockProvider creates a new instance of mockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockProvider {
	mock := &mockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockProvider is an autogenerated mock type for the Provider type
type mockProvider struct {
	mock.Mock
}

type mockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockProvider) EXPECT() *mockProvider_Expecter {
	return &mockProvider_Expecter{mock: &_m.Mock}
}

// Provide provides a mock function for the type mockProvider
func (_mock *mockProvider) Provide(ctx context.Context) (<-chan Delivery, <-chan error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 <-chan Delivery
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan Delivery, <-chan error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan Delivery); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// mockProvider_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type mockProvider_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockProvider_Expecter) Provide(ctx any) *mockProvider_Provide_Call {
	return &mockProvider_Provide_Call{Call: _e.mock.On("Provide", ctx)}
}

func (_c *mockProvider_Provide_Call) Run(run func(ctx context.Context)) *mockProvider_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockProvider_Provide_Call) Return(deliveryCh <-chan Delivery, errCh <-chan error) *mockProvider_Provide_Call {
	_c.Call.Return(deliveryCh, errCh)
	return _c
}

func (_c *mockProvider_Provide_Call) RunAndReturn(run func(ctx context.Context) (<-chan Delivery, <-chan error)) *mockProvider_Provide_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPublisher creates a new instance of mockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPublisher {
	mock := &mockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPublisher is an autogenerated mock type for the Publisher type
type mockPublisher struct {
	mock.Mock
}

type mockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPublisher) EXPECT() *mockPublisher_Expecter {
	return &mockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type mockPublisher
func (_mock *mockPublisher) Publish(ctx context.Context, env *Envelope) error {
	ret := _mock.Called(ctx, env)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Envelope) error); ok {
		r0 = returnFunc(ctx, env)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type mockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - env *Envelope
func (_e *mockPublisher_Expecter) Publish(ctx any, env any) *mockPublisher_Publish_Call {
	return &mockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, env)}
}

func (_c *mockPublisher_Publish_Call) Run(run func(ctx context.Context, env *Envelope)) *mockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Envelope
		if args[1] != nil {
			arg1 = args[1].(*Envelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPublisher_Publish_Call) Return(err error) *mockPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, env *Envelope) error) *mockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRepository creates a new instance of mockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRepository {
	mock := &mockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRepository is an autogenerated mock type for the Repository type
type mockRepository struct {
	mock.Mock
}

type mockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRepository) EXPECT() *mockRepository_Expecter {
	return &mockRepository_Expecter{mock: &_m.Mock}
}

// ClaimPending provides a mock function for the type mockRepository
func (_mock *mockRepository) ClaimPending(ctx context.Context, limit int) ([]Message, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimPending")
	}

	var r0 []Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]Message, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []Message); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRepository_ClaimPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimPending'
type mockRepository_ClaimPending_Call struct {
	*mock.Call
}

// ClaimPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *mockRepository_Expecter) ClaimPending(ctx any, limit any) *mockRepository_ClaimPending_Call {
	return &mockRepository_ClaimPending_Call{Call: _e.mock.On("ClaimPending", ctx, limit)}
}

func (_c *mockRepository_ClaimPending_Call) Run(run func(ctx context.Context, limit int)) *mockRepository_ClaimPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockRepository_ClaimPending_Call) Return(messages []Message, err error) *mockRepository_ClaimPending_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *mockRepository_ClaimPending_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]Message, error)) *mockRepository_ClaimPending_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRouter creates a new instance of mockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRouter {
	mock := &mockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRouter is an autogenerated mock type for the Router type
type mockRouter struct {
	mock.Mock
}

type mockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRouter) EXPECT() *mockRouter_Expecter {
	return &mockRouter_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type mockRouter
func (_mock *mockRouter) Resolve(msg *Message) (Route, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 Route
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Message) (Route, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func(*Message) Route); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Route)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Message) error); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockRouter_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type mockRouter_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - msg *Message
func (_e *mockRouter_Expecter) Resolve(msg any) *mockRouter_Resolve_Call {
	return &mockRouter_Resolve_Call{Call: _e.mock.On("Resolve", msg)}
}

func (_c *mockRouter_Resolve_Call) Run(run func(msg *Message)) *mockRouter_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Message
		if args[0] != nil {
			arg0 = args[0].(*Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockRouter_Resolve_Call) Return(route Route, err error) *mockRouter_Resolve_Call {
	_c.Call.Return(route, err)
	return _c
}

func (_c *mockRouter_Resolve_Call) RunAndReturn(run func(msg *Message) (Route, error)) *mockRouter_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRowQuerier creates a new instance of mockRowQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRowQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRowQuerier {
	mock := &mockRowQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockRowQuerier is an autogenerated mock type for the RowQuerier type
type mockRowQuerier struct {
	mock.Mock
}

type mockRowQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRowQuerier) EXPECT() *mockRowQuerier_Expecter {
	return &mockRowQuerier_Expecter{mock: &_m.Mock}
}

// QueryRow provides a mock function for the type mockRowQuerier
func (_mock *mockRowQuerier) QueryRow(ctx context.Context, query string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// mockRowQuerier_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type mockRowQuerier_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *mockRowQuerier_Expecter) QueryRow(ctx any, query any, args ...any) *mockRowQuerier_QueryRow_Call {
	return &mockRowQuerier_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{ctx, query}, args...)...)}
}

func (_c *mockRowQuerier_QueryRow_Call) Run(run func(ctx context.Context, query string, args ...any)) *mockRowQuerier_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mockRowQuerier_QueryRow_Call) Return(row pgx.Row) *mockRowQuerier_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *mockRowQuerier_QueryRow_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) pgx.Row) *mockRowQuerier_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}
